# -*- coding: utf-8 -*-
"""K Means.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Ff_vyWJTQtkGNoQFInf7mdnHcFcuwrdO
"""

# Commented out IPython magic to ensure Python compatibility.
import seaborn as sns
import matplotlib.pyplot as plt
# %matplotlib inline

from sklearn.datasets import make_blobs

data=make_blobs(n_samples=200,n_features=2,centers=4,cluster_std=1.8,random_state=101)

data[0]

data[1]

data[0].shape

plt.scatter(data[0][:,0],data[0][:,1])

plt.scatter(data[0][:,0],data[0][:,1],c=data[1],cmap="rainbow")

from sklearn.cluster import KMeans

kmeans=KMeans(n_clusters=4)

kmeans.fit(data[0])

kmeans.cluster_centers_

#predicted label
kmeans.labels_

#original label
data[1]

fig,(ax1,ax2)=plt.subplots(1,2, sharey=True,figsize=(10,6))
ax1.set_title("KMeans")
ax1.scatter(data[0][:,0],data[0][:,1],c=kmeans.labels_,cmap="rainbow")
ax2.set_title("Original")
ax2.scatter(data[0][:,0],data[0][:,1],c=data[1])

