# -*- coding: utf-8 -*-
"""PCA.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1rXDkmaOieEBEpK1m7gNp-FMVFSI-Y0Fn
"""

# Commented out IPython magic to ensure Python compatibility.
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
# %matplotlib inline

from sklearn.datasets import load_breast_cancer

cancer=load_breast_cancer()

cancer.keys()

df=pd.DataFrame(cancer["data"],columns=cancer["feature_names"])

df.head()

from sklearn.preprocessing import StandardScaler

scaler=StandardScaler()

scaler.fit(df)

scaled_data=scaler.transform(df)

from sklearn.decomposition import PCA

pca=PCA(n_components=2)

pca.fit(scaled_data)

x_pca=pca.transform(scaled_data)

scaled_data.shape

x_pca.shape

plt.figure(figsize=(10,8))
plt.scatter(x_pca[:,0],x_pca[:,1],c=cancer["target"])
plt.xlabel("1st components")
plt.ylabel("2nd components")

type(pca)

type(x_pca)

pca.components_

df_comp=pd.DataFrame(pca.components_,columns=cancer["feature_names"])

plt.figure(figsize=(15,10))
sns.heatmap(df_comp)

cancer["target_names"]

cancer["target"]

