# -*- coding: utf-8 -*-
"""Liner Regression (single variable).ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1qpXl1aVb341k37dhGmo-40tpWjfw_5PE
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

# Commented out IPython magic to ensure Python compatibility.
# %matplotlib inline

from sklearn import linear_model

from google.colab import files

uploaded = files.upload()

df=pd.read_csv("houses.csv")
df

plt.scatter(df["AREA in SQFT"],df["PRICE"])

sns.lmplot("AREA in SQFT","PRICE",df)

lm=linear_model.LinearRegression()

lm.fit(df[["AREA in SQFT"]],df.PRICE)

lm.predict([[4232]])

#checking with y=mx+c
print(lm.coef_)
print(lm.intercept_)

#cross checking
172.4137931*4232+65517.24137931038

#using this to find multiple area's price
from google.colab import files

uploaded = files.upload()

new=pd.read_csv("newarea.csv")
new

predicted_prices=lm.predict(new)

predicted_prices

new["PRICES"]=predicted_prices

new

new.to_csv("areas with predicted price.csv",index=False)

new

from google.colab import files



files.download('areas with predicted price.csv')

